save_best: True
plot_agents: False
verbose: False

log_dir: ./tmp
video_dir: ${log_dir}/videos

hydra:
      run:
            dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

optuna:
      study:
        _target_: optuna.create_study
        study_name: cem_swimmer
        direction: maximize
        # for a list of optuna pruners, this is here: https://optuna.readthedocs.io/en/stable/reference/pruners.html
        pruner:
          _target_: optuna.pruners.MedianPruner
          n_startup_trials: 5
          n_warmup_steps: 5
          interval_steps: 1
      optimize:
        n_trials: 10000
        timeout: 3600
        n_jobs: 1

logger:
      classname: bbrl.utils.logger.WandbLogger
      project: "cem_study"
      group: "tune_cem"
      tags: "hp_cem"
      job_type: test
      log_dir: ${log_dir}
      cache_size: 10000
      every_n_seconds: 10
      verbose: False

algorithm:
      seed:
            train: 335
            eval: 983
            actor: 123
            torch: 7
      sigma: 0.1
      n_envs_train: 1
      n_envs_eval: 10
      n_steps: 300_000
      noise_multiplier: 0.99
      pop_size:
            suggest_type: categorical
            choices:
                  - 10
                  - 15
                  - 20
      elites_nb:
            suggest_type: categorical
            choices:
                  - 5
                  - 7
                  - 9
      actor_type: ContinuousDeterministicActor
      architecture:
            actor_hidden_size:
                  suggest_type: categorical
                  choices:
                        - [4, 4]
                        - [8, 8]
                        - [16, 16]
                        - [40, 30]

# Note: Swimmer-v3 is deprecated, but Swimmer-v4 does not seem to accept an xml_file
gym_env:
      env_name: SwimmerBBRLEnv-v0
      xml_file: swimmer5.xml
