save_best: True
plot_agents: False
verbose: False

log_dir: ./tmp
video_dir: ${log_dir}/videos

hydra:
      run:
            dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
            classname: bbrl.utils.logger.TFLogger
            log_dir: ./dqn_logs/
            verbose: False
            every_n_seconds: 10

algorithm:
      seed:
            train: 335
            eval: 9
            actor: 123
            torch: 7
      sigma: 0.1
      n_envs_train: 1
      n_envs_eval: 10
      n_steps: 5_000_000
      noise_multiplier: 0.99
      pop_size: 16
      elites_nb: 5
      actor_type: ContinuousDeterministicActor
      architecture:
            actor_hidden_size: [19, 19]

# Note: Swimmer-v3 is deprecated, but Swimmer-v4 does not seem to accept an xml_file
gym_env:
      env_name: SwimmerBBRLEnv-v0
      xml_file: swimmer3.xml
