    save_best: True
    plot_agents: False

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./a2c_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
       seed:
          train: 2
          eval: 9
          q: 1
          act: 2
          torch: 7
      max_grad_norm: 0.5
      n_steps_train: 20
      n_steps: 30000
      n_envs: 1
      eval_interval: 2000
      nb_evals: 1
      max_grad_norm: 0.5
      gae: 0.99
      discount_factor: 0.99999
      entropy_coef: 2.55e-5
      critic_coef: 0.6
      a2c_coef: 1
      actor_type: TunableVarianceContinuousActor
      architecture:
        actor_hidden_size: [24, 36]
        critic_hidden_size: [24, 36]

    gym_env:
      env_name: Swimmer-v3

    optimizer:
      classname: torch.optim.Adam
      lr: 0.001
