    save_best: True
    plot_agents: True

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./reinforce_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:

      seed:
        env: 2
        q: 1
        act: 2
        torch: 7

      n_envs: 50
      nb_episodes: 1000
      discount_factor: 0.95
      entropy_coef: 0
      critic_coef: 1
      actor_coef: 1
      gae: 0.8
      actor_type: DiscreteActor
      architecture:
        actor_hidden_size: [32]
        critic_hidden_size: [24, 36]

    gym_env:
      env_name: CartPole-v1

    optimizer:
      classname: torch.optim.Adam
      lr: 0.001
