save_best: True
plot_agents: True
collect_stats: True
stats_directory: ../../../src/bbrl_algos/algos/algorithm_stats/

logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./sac_logs/
      verbose: False
      every_n_seconds: 10

algorithm:

      seed:
            train: 1
            eval: 99
            q: 123
            explorer: 456
            torch: 789

      nb_seeds: 1
      n_envs: 8
      n_steps_train: 32
      n_steps: 300_000
      max_grad_norm: 0.5
      buffer_size: 1e6
      batch_size: 256
      eval_interval: 2_000
      nb_evals: 10
      learning_starts: 10_000
      tau_target: 0.05
      discount_factor: 0.98
      entropy_mode: "auto" # "auto" or "fixed"
      init_entropy_coef: 2e-7
      actor_type: SquashedGaussianActor
      architecture:
            actor_hidden_size: [64, 64]
            critic_hidden_size: [256, 256]

gym_env:
      env_name: CartPoleContinuous-v1

actor_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

critic_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

entropy_coef_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3
