save_best: True
plot_agents: True
collect_stats: True
stats_directory: ../../../src/bbrl_algos/algos/algorithm_stats/

logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./sac_logs/
      verbose: False
      every_n_seconds: 10

algorithm:

      seed:
            train: 335
            eval: 983
            q: 123
            explorer: 456
            torch: 789

      max_grad_norm: 0.5
      n_envs: 8
      n_steps_train: 20
      n_steps: 300_000
      eval_interval: 2000
      buffer_size: 2e5
      batch_size: 64
      learning_starts: 10000
      nb_evals: 10
      tau_target: 0.05
      discount_factor: 0.95
      entropy_coef: 2.55e-5
      entropy_mode: "auto" # "auto" or "fixed"
      init_entropy_coef: 2e-7
      architecture:
            actor_hidden_size: [256, 256]
            critic_hidden_size: [256, 256]

gym_env:
      env_name: CartPole-v1

actor_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

critic_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

entropy_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

entropy_coef_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3
