save_best: True
plot_agents: False
verbose: False

log_dir: ./tmp
video_dir: ${log_dir}/videos

hydra:
      run:
            dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
      classname: bbrl.utils.logger.WandbLogger
      project: "cem_study"
      group: "tune_cem"
      tags: "hp_cem"
      job_type: test
      log_dir: ${log_dir}
      cache_size: 10000
      every_n_seconds: 10
      verbose: False

algorithm:
      seed:
            train: 335
            eval: 9
            actor: 123
            torch: 7
      sigma: 0.1
      n_envs: 1
      nb_evals: 10
      n_steps: 1_000_000
      noise_multiplier: 0.99
      pop_size: 15
      elites_nb: 5
      actor_type: ContinuousDeterministicActor
      architecture:
            actor_hidden_size: [19, 19]

# Note: Swimmer-v3 is deprecated, but Swimmer-v4 does not seem to accept an xml_file
gym_env:
      env_name: SwimmerBBRLEnv-v0
      xml_file: swimmer5.xml
