      save_best: False
      plot_agents: False
      collect_stats: True

      logger:
            classname: bbrl.utils.logger.TFLogger
            log_dir: ./ppo_logs/
            verbose: False
            every_n_seconds: 10

      algorithm:
            seed:
                  train: 335
                  eval: 983
                  policy: 123
                  torch: 789

            max_grad_norm: 0.9
            n_envs: 8
            n_steps_train: 256
            n_steps: 70000
            eval_interval: 4000
            nb_evals: 10
            gae: 0.99
            discount_factor: 0.999999
            opt_epochs: 3
            batch_size: 16
            clip_range: 0.2
            clip_range_vf: 0
            entropy_coef: 2e-7
            critic_coef: 0.4
            policy_coef: 1
            policy_type: ConstantVarianceContinuousActor
            architecture:
                  policy_hidden_size: [64]
                  critic_hidden_size: [64]

      gym_env:
            env_name: Swimmer-v3

      optimizer:
            classname: torch.optim.Adam
            lr: 0.002
