    save_best: True
    plot_agents: True
    collect_stats: True


    log_dir: ./tmp
    video_dir: ${log_dir}/videos

    hydra:
      run:
        dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ${log_dir}
      cache_size: 10000
      every_n_seconds: 10
      verbose: False

    algorithm:

      seed:
        train: 5
        eval: 9
        q: 1
        act: 2
        explorer: 4
        torch: 7

      max_grad_norm: 0.5
      optim_n_updates: 20
      n_envs: 1
      n_steps_train: 100
      n_steps: 6_000
      buffer_size: 2e5
      batch_size: 128
      tau_target: 0.05
      eval_interval: 2000
      learning_starts: 10000
      nb_evals: 100
      action_noise: 0.1
      discount_factor: 0.99
      architecture:
        actor_hidden_size: [128, 128]
        critic_hidden_size: [256, 256]

    gym_env:
      classname: __main__.make_gym_env
      env_name: Pendulum-v1

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

    critic_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3
