    save_best: True
    plot_agents: True

    log_dir: ./tmp
    video_dir: ${log_dir}/videos

    hydra:
      run:
        dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

    logger:
      classname: bbrl.utils.logger.WandbLogger
      project: "ddpg_study"
      group: "tune_ddpg_pendulum"
      tags: "hp_ddpg_pendulum"
      job_type: test
      log_dir: ${log_dir}
      cache_size: 10000
      every_n_seconds: 10
      verbose: False

    algorithm:

      seed:
        train: 2
        eval: 9
        q: 1
        act: 2
        explorer: 4
        torch: 7

      max_grad_norm: 0.5
      optim_n_updates: 3
      n_envs: 1
      n_steps_train: 100
      n_steps: 100_000
      buffer_size: 2e5
      batch_size: 64
      tau_target: 0.05
      eval_interval: 2000
      learning_starts: 10000
      nb_evals: 10
      action_noise: 0.1
      discount_factor: 0.98
      architecture:
        actor_hidden_size: [400, 300]
        critic_hidden_size: [400, 300]

    gym_env:
      env_name: Pendulum-v1

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

    critic_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3
