# Caution: use only the 'suggest_type' in case of using optuna
save_best: True
plot_agents: False
collect_stats: True

log_dir: ./tmp
video_dir: ${log_dir}/videos

hydra:
  run:
    dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
  classname: bbrl.utils.logger.TFLogger
  log_dir: ${log_dir}
  cache_size: 10000
  every_n_seconds: 10
  verbose: False

gym_env:
  env_name: CartPole-v1
  render_mode: rgb_array

algorithm:
  architecture:
    hidden_sizes: [64, 64]

  seed:
    train: 32
    eval: 99
    q: 123
    explorer: 456
    torch: 789

  explorer:
    epsilon_start: 0.7
    epsilon_end: 0.2
    decay: 0.999

  buffer:
    max_size: 150000
    batch_size: 256
    learning_starts: 2000

  target_critic_update_interval: 100
  max_grad_norm: 0.5

  nb_evals: 10
  n_envs: 10
  n_steps_train: 50

  optim_n_updates: 3
  discount_factor: 0.9

  n_steps: 300_000
  eval_interval: 1000


optimizer:
  classname: torch.optim.Adam
  lr: 5e-4
