    save_best: True
    plot_agents: True


    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./a2c_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed:
          train: 2
          eval: 9
          q: 1
          act: 2
          torch: 7
      max_grad_norm: 0.5
      n_envs: 8
      n_steps_train: 20
      n_steps: 30000
      eval_interval: 2000
      nb_evals: 10
      max_grad_norm: 0.5
      gae: 0.8
      discount_factor: 0.99
      entropy_coef: 2.55e-4
      critic_coef: 0.5
      a2c_coef: 1
      actor_type: ConstantVarianceContinuousActor
      architecture:
        actor_hidden_size: [25, 25]
        critic_hidden_size: [25, 25]

    gym_env:
      env_name: CartPoleContinuous-v1

    optimizer:
      classname: torch.optim.Adam
      lr: 0.001
