save_best: False
plot_agents: False
collect_stats: False

log_dir: ./tmp
video_dir: ${log_dir}/videos

hydra:
  run:
    dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

optuna:
  study:
    _target_: optuna.create_study
    study_name: ddpg_pendulum
    direction: maximize
    # for a list of optuna pruners, this is here: https://optuna.readthedocs.io/en/stable/reference/pruners.html
    pruner:
      _target_: optuna.pruners.MedianPruner
      n_startup_trials: 0
      n_warmup_steps: 5
      interval_steps: 1
  optimize:
    n_trials: 10000
    timeout: 3600
    n_jobs: -1

logger:
  classname: bbrl.utils.logger.TFLogger
  log_dir: ${log_dir}
  cache_size: 10000
  every_n_seconds: 10
  verbose: False

algorithm:
  seed:
    train: 2
    eval: 9
    q: 1
    act: 2
    explorer: 4
    torch: 7

  max_grad_norm:
    suggest_type: float
    low: .5
    high: 3

  optim_n_updates:
    suggest_type: int
    low: 1
    high: 10
  n_envs: 10
  n_steps_train: 64
  n_steps: 300_000
  buffer_size: 2e5
  batch_size: 256
  tau_target: 
    suggest_type: float
    low: 0.01
    high: 0.1
  eval_interval: 4000
  learning_starts: 2000
  nb_evals: 10
  action_noise: 0.1
  discount_factor:
    suggest_type: categorical
    choices:
      - 0.9
      - 0.99
      - 0.999
  architecture:
    actor_hidden_size: [512, 512, 256]
    critic_hidden_size: [512, 512, 256]

gym_env:
  classname: __main__.make_gym_env
  env_name: Pendulum-v1

actor_optimizer:
  classname: torch.optim.Adam
  lr: 1e-3

critic_optimizer:
  classname: torch.optim.Adam
  lr: 1e-3