    save_best: True
    plot_agents: True
    collect_stats: False

    log_dir: ./tmp
    video_dir: ${log_dir}/videos

    hydra:
      run:
        dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

    optuna:
      study:
        _target_: optuna.create_study
        study_name: ddpg_pendulum
        direction: maximize
        # for a list of optuna pruners, this is here: https://optuna.readthedocs.io/en/stable/reference/pruners.html
        pruner:
          _target_: optuna.pruners.MedianPruner
          n_startup_trials: 5
          n_warmup_steps: 5
          interval_steps: 1
      optimize:
        n_trials: 10000
        timeout: 3600
        n_jobs: 1

    logger:
      classname: bbrl.utils.logger.WandbLogger
      project: "ddpg_study"
      group: "tune_ddpg"
      tags: "hp_ddpg"
      job_type: test
      log_dir: ${log_dir}
      cache_size: 10000
      every_n_seconds: 10
      verbose: False

    algorithm:

      seed:
        train: 2
        eval: 9
        q: 1
        act: 2
        explorer: 4
        torch: 7

      max_grad_norm: 0.5
      optim_n_updates:
        suggest_type: categorical
        choices:
          - 1
          - 3
          - 4
          - 6
          - 10
          - 20
      n_envs: 1
      n_steps_train: 100
      n_steps: 100_000
      buffer_size: 2e5
      batch_size:
        suggest_type: categorical
        choices:
          - 64
          - 128
      tau_target: 0.05
      eval_interval: 2000
      learning_starts: 10000
      nb_evals: 10
      action_noise: 0.1
      discount_factor:
        suggest_type: categorical
        choices:
          - 0.9
          - 0.99
          - 0.999
      architecture:
        actor_hidden_size:
          suggest_type: categorical
          choices:
            - [64, 64]
            - [128, 128]
            - [256, 256]
            - [400, 300]
        critic_hidden_size:
          suggest_type: categorical
          choices:
            - [64, 64]
            - [128, 128]
            - [256, 256]
            - [400, 300]

    gym_env:
      classname: __main__.make_gym_env
      env_name: Pendulum-v1

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

    critic_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3
